# Generated by Django 4.2.7 on 2023-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='время последнего изменения'),
        ),
    ]
