# Generated by Django 4.2.7 on 2023-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sum_of_pay',
            field=models.PositiveIntegerField(default=1, verbose_name='сумма оплаты'),
        ),
    ]
