# Generated by Django 4.2.7 on 2023-11-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='what_pay',
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='education.course', verbose_name='купил курс'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='education.lesson', verbose_name='купил урок'),
        ),
    ]
