# Generated by Django 4.2.7 on 2023-11-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_payment_user'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='course',
        ),
    ]
