# Generated by Django 4.2.7 on 2023-11-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_lesson_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to=None,
        ),
    ]
