# Generated by Django 4.2.7 on 2023-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='цена курса'),
        ),
    ]
