# Generated by Django 4.2.7 on 2023-11-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_course_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
