# Generated by Django 4.2.7 on 2023-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='время последнего изменения'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='время последнего изменения'),
        ),
    ]
