# Generated by Django 4.2.7 on 2023-12-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_course_update_the_last_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='update_the_last_one',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время прошлого изменения'),
        ),
    ]
