# Generated by Django 4.2.7 on 2023-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_alter_course_update_the_last_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_send_update',
            field=models.BooleanField(default=False, verbose_name='отправлено ли сообщение об обновлении курса'),
        ),
    ]
